// <auto-generated />
using System;
using FantaxyWebApplication.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FantaxyWebApplication.Migrations
{
    [DbContext(typeof(FantaxyContext))]
    [Migration("20240413114447_Migrant-1")]
    partial class Migrant1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.Chat", b =>
                {
                    b.Property<int>("IdChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChat"), 1L, 1);

                    b.Property<int?>("IdPlanet")
                        .HasColumnType("int");

                    b.Property<string>("OwnerLogin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdChat")
                        .HasName("PK__Chats__3817F38CC76E5C7C");

                    b.HasIndex("IdPlanet");

                    b.HasIndex("OwnerLogin");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.ChatFile", b =>
                {
                    b.Property<int>("IdChatFiles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChatFiles"), 1L, 1);

                    b.Property<int>("IdChat")
                        .HasColumnType("int");

                    b.Property<string>("PathFile")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdChatFiles")
                        .HasName("PK__ChatFile__9AE1324E131733DB");

                    b.HasIndex("IdChat");

                    b.ToTable("ChatFiles");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.ChatMessage", b =>
                {
                    b.Property<int>("IdChatMessages")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChatMessages"), 1L, 1);

                    b.Property<int?>("IdChat")
                        .HasColumnType("int");

                    b.Property<string>("LoginOwner")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("IdChatMessages")
                        .HasName("PK__ChatMess__7909324CC7C01757");

                    b.HasIndex("IdChat");

                    b.HasIndex("LoginOwner");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.ChatRole", b =>
                {
                    b.Property<int>("IdChatRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChatRole"), 1L, 1);

                    b.Property<string>("ChatRole1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ChatRole");

                    b.HasKey("IdChatRole")
                        .HasName("PK__ChatRole__33BF2B4FB12D4334");

                    b.ToTable("ChatRole", (string)null);
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.ChatsInfo", b =>
                {
                    b.Property<int>("IdChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Background")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ChatDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ChatName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdChat")
                        .HasName("PK__ChatsInf__3817F38C531E447C");

                    b.ToTable("ChatsInfo", (string)null);
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.ChatsUsersChatRole", b =>
                {
                    b.Property<int>("IdCU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdC_U");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCU"), 1L, 1);

                    b.Property<int?>("IdChat")
                        .HasColumnType("int");

                    b.Property<int?>("IdChatRole")
                        .HasColumnType("int");

                    b.Property<string>("LoginUsers")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCU")
                        .HasName("PK__Chats_Us__0FA070803DFA5C56");

                    b.HasIndex("IdChat");

                    b.HasIndex("IdChatRole");

                    b.HasIndex("LoginUsers");

                    b.ToTable("Chats_Users_ChatRole", (string)null);
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.Comment", b =>
                {
                    b.Property<int>("IdComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComment"), 1L, 1);

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OwnerLogin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdComment")
                        .HasName("PK__Comments__57C9AD58DEF939D9");

                    b.HasIndex("OwnerLogin");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.CommentsFile", b =>
                {
                    b.Property<int>("IdCommentFiles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCommentFiles"), 1L, 1);

                    b.Property<int>("IdComment")
                        .HasColumnType("int");

                    b.Property<string>("PathFile")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdCommentFiles")
                        .HasName("PK__Comments__7D54E3F8B14EDFAC");

                    b.HasIndex("IdComment");

                    b.ToTable("CommentsFiles");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.GlobalRole", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"), 1L, 1);

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRole")
                        .HasName("PK__GlobalRo__B4369054D6C8C840");

                    b.ToTable("GlobalRole", (string)null);
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.GlobalRoleUser", b =>
                {
                    b.Property<int>("IdGlRU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdGlR_U");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGlRU"), 1L, 1);

                    b.Property<int?>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("UserLogin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdGlRU")
                        .HasName("PK__GlobalRo__187B74EF3CE7A76A");

                    b.HasIndex("IdRole");

                    b.HasIndex("UserLogin");

                    b.ToTable("GlobalRole_Users", (string)null);
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.GlobalUsersInfo", b =>
                {
                    b.Property<string>("UserLogin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainBackground")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileBackground")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("UserTelephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserLogin")
                        .HasName("PK__GlobalUs__7F8E8D5F5A0EC263");

                    b.ToTable("GlobalUsersInfo", (string)null);
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.LikesPlanet", b =>
                {
                    b.Property<int>("IdLikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLikes"), 1L, 1);

                    b.Property<int?>("IdPlanet")
                        .HasColumnType("int");

                    b.Property<string>("LoginOwner")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdLikes")
                        .HasName("PK__Likes_Pl__3FDC4886B5DE3F34");

                    b.HasIndex("IdPlanet");

                    b.HasIndex("LoginOwner");

                    b.ToTable("Likes_Planets", (string)null);
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.Planet", b =>
                {
                    b.Property<int>("IdPlanet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanet"), 1L, 1);

                    b.Property<string>("CuratorLogin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OwnerLogin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPlanet")
                        .HasName("PK__Planets__12FD4B354560ABC6");

                    b.HasIndex("CuratorLogin");

                    b.HasIndex("OwnerLogin");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.PlanetInfo", b =>
                {
                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("IdPlanet")
                        .HasColumnType("int");

                    b.Property<string>("MainBackground")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PlanetDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PlanetName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfileBackground")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasIndex("IdPlanet");

                    b.ToTable("PlanetInfo", (string)null);
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.PlanetRole", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"), 1L, 1);

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRole")
                        .HasName("PK__PlanetRo__B4369054FD7EA7E3");

                    b.ToTable("PlanetRole", (string)null);
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.PlanetRoleUser", b =>
                {
                    b.Property<int>("IdPlRU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPlR_U");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlRU"), 1L, 1);

                    b.Property<int?>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("UserLogin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPlRU")
                        .HasName("PK__PlanetRo__475A5094A7C77AB6");

                    b.HasIndex("IdRole");

                    b.HasIndex("UserLogin");

                    b.ToTable("PlanetRole_Users", (string)null);
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.PlanetUser", b =>
                {
                    b.Property<int>("IdPlU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPl_U");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlU"), 1L, 1);

                    b.Property<int?>("IdPlanet")
                        .HasColumnType("int");

                    b.Property<string>("UserLogin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPlU")
                        .HasName("PK__Planet_U__FB8132F5326A75DA");

                    b.HasIndex("IdPlanet");

                    b.HasIndex("UserLogin");

                    b.ToTable("Planet_Users", (string)null);
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.PlanetUsersInfo", b =>
                {
                    b.Property<int>("IdPlUsInfo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPlUsInfo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlUsInfo"), 1L, 1);

                    b.Property<string>("Avatar")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("IdPlanet")
                        .HasColumnType("int");

                    b.Property<string>("MainBackground")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProfileBackground")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("UserDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdPlUsInfo")
                        .HasName("PK__PlanetUs__75271A21F6503D47");

                    b.HasIndex("IdPlanet");

                    b.HasIndex("UserLogin");

                    b.ToTable("PlanetUsersInfo", (string)null);
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.Post", b =>
                {
                    b.Property<int>("IdPost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPost"), 1L, 1);

                    b.Property<int?>("IdPlanet")
                        .HasColumnType("int");

                    b.Property<string>("OwnerLogin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPost")
                        .HasName("PK__Posts__F8DCBD4D672470BC");

                    b.HasIndex("IdPlanet");

                    b.HasIndex("OwnerLogin");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.Status", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatus"), 1L, 1);

                    b.Property<string>("StatusName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdStatus")
                        .HasName("PK__Statuses__B450643AB6A8176B");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.StatusesChat", b =>
                {
                    b.Property<int>("IdStPl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdSt_Pl");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStPl"), 1L, 1);

                    b.Property<int?>("IdPlanet")
                        .HasColumnType("int");

                    b.Property<int?>("IdStatus")
                        .HasColumnType("int");

                    b.HasKey("IdStPl")
                        .HasName("PK__Statuses__2E9E5A44374573E4");

                    b.HasIndex("IdPlanet");

                    b.HasIndex("IdStatus");

                    b.ToTable("Statuses_Chats", (string)null);
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.StatusesPlanet", b =>
                {
                    b.Property<int>("IdStPl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdSt_Pl");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStPl"), 1L, 1);

                    b.Property<int?>("IdPlanet")
                        .HasColumnType("int");

                    b.Property<int?>("IdStatus")
                        .HasColumnType("int");

                    b.HasKey("IdStPl")
                        .HasName("PK__Statuses__2E9E5A440026F635");

                    b.HasIndex("IdPlanet");

                    b.HasIndex("IdStatus");

                    b.ToTable("Statuses_Planet", (string)null);
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.User", b =>
                {
                    b.Property<string>("UserLogin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("UserLogin")
                        .HasName("PK__Users__7F8E8D5F84BEA75E");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.UserStatus", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatus"), 1L, 1);

                    b.Property<string>("NameStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdStatus")
                        .HasName("PK__UserStat__B450643A90CECD15");

                    b.ToTable("UserStatuses");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.UserStatusesStatus", b =>
                {
                    b.Property<int>("IdUsS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdUS_S");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsS"), 1L, 1);

                    b.Property<int?>("IdStatus")
                        .HasColumnType("int");

                    b.Property<string>("UserLogin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUsS")
                        .HasName("PK__UserStat__BF8A4F8E2C09891B");

                    b.HasIndex("IdStatus");

                    b.HasIndex("UserLogin");

                    b.ToTable("UserStatuses_Statuses", (string)null);
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.Chat", b =>
                {
                    b.HasOne("FantaxyWebApplication.Models.Entities.Planet", "IdPlanetNavigation")
                        .WithMany("Chats")
                        .HasForeignKey("IdPlanet")
                        .HasConstraintName("FK__Chats__IdPlanet__5DCAEF64");

                    b.HasOne("FantaxyWebApplication.Models.Entities.User", "OwnerLoginNavigation")
                        .WithMany("Chats")
                        .HasForeignKey("OwnerLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Chats__OwnerLogi__5EBF139D");

                    b.Navigation("IdPlanetNavigation");

                    b.Navigation("OwnerLoginNavigation");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.ChatFile", b =>
                {
                    b.HasOne("FantaxyWebApplication.Models.Entities.Chat", "IdChatNavigation")
                        .WithMany("ChatFiles")
                        .HasForeignKey("IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChatFiles__IdCha__797309D9");

                    b.Navigation("IdChatNavigation");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.ChatMessage", b =>
                {
                    b.HasOne("FantaxyWebApplication.Models.Entities.Chat", "IdChatNavigation")
                        .WithMany("ChatMessages")
                        .HasForeignKey("IdChat")
                        .HasConstraintName("FK__ChatMessa__IdCha__02FC7413");

                    b.HasOne("FantaxyWebApplication.Models.Entities.User", "LoginOwnerNavigation")
                        .WithMany("ChatMessages")
                        .HasForeignKey("LoginOwner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__ChatMessa__Login__02084FDA");

                    b.Navigation("IdChatNavigation");

                    b.Navigation("LoginOwnerNavigation");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.ChatsInfo", b =>
                {
                    b.HasOne("FantaxyWebApplication.Models.Entities.Chat", "IdChatNavigation")
                        .WithOne("ChatsInfo")
                        .HasForeignKey("FantaxyWebApplication.Models.Entities.ChatsInfo", "IdChat")
                        .IsRequired()
                        .HasConstraintName("FK__ChatsInfo__IdCha__68487DD7");

                    b.Navigation("IdChatNavigation");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.ChatsUsersChatRole", b =>
                {
                    b.HasOne("FantaxyWebApplication.Models.Entities.Chat", "IdChatNavigation")
                        .WithMany("ChatsUsersChatRoles")
                        .HasForeignKey("IdChat")
                        .HasConstraintName("FK__Chats_Use__IdCha__6383C8BA");

                    b.HasOne("FantaxyWebApplication.Models.Entities.ChatRole", "IdChatRoleNavigation")
                        .WithMany("ChatsUsersChatRoles")
                        .HasForeignKey("IdChatRole")
                        .HasConstraintName("FK__Chats_Use__IdCha__656C112C");

                    b.HasOne("FantaxyWebApplication.Models.Entities.User", "LoginUsersNavigation")
                        .WithMany("ChatsUsersChatRoles")
                        .HasForeignKey("LoginUsers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Chats_Use__Login__6477ECF3");

                    b.Navigation("IdChatNavigation");

                    b.Navigation("IdChatRoleNavigation");

                    b.Navigation("LoginUsersNavigation");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.Comment", b =>
                {
                    b.HasOne("FantaxyWebApplication.Models.Entities.User", "OwnerLoginNavigation")
                        .WithMany("Comments")
                        .HasForeignKey("OwnerLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Comments__OwnerL__7C4F7684");

                    b.Navigation("OwnerLoginNavigation");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.CommentsFile", b =>
                {
                    b.HasOne("FantaxyWebApplication.Models.Entities.Comment", "IdCommentNavigation")
                        .WithMany("CommentsFiles")
                        .HasForeignKey("IdComment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CommentsF__IdCom__7F2BE32F");

                    b.Navigation("IdCommentNavigation");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.GlobalRoleUser", b =>
                {
                    b.HasOne("FantaxyWebApplication.Models.Entities.GlobalRole", "IdRoleNavigation")
                        .WithMany("GlobalRoleUsers")
                        .HasForeignKey("IdRole")
                        .HasConstraintName("FK__GlobalRol__IdRol__4F7CD00D");

                    b.HasOne("FantaxyWebApplication.Models.Entities.User", "UserLoginNavigation")
                        .WithMany("GlobalRoleUsers")
                        .HasForeignKey("UserLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__GlobalRol__UserL__4E88ABD4");

                    b.Navigation("IdRoleNavigation");

                    b.Navigation("UserLoginNavigation");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.GlobalUsersInfo", b =>
                {
                    b.HasOne("FantaxyWebApplication.Models.Entities.User", "UserLoginNavigation")
                        .WithOne("GlobalUsersInfo")
                        .HasForeignKey("FantaxyWebApplication.Models.Entities.GlobalUsersInfo", "UserLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__GlobalUse__UserL__3C69FB99");

                    b.Navigation("UserLoginNavigation");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.LikesPlanet", b =>
                {
                    b.HasOne("FantaxyWebApplication.Models.Entities.Planet", "IdPlanetNavigation")
                        .WithMany("LikesPlanets")
                        .HasForeignKey("IdPlanet")
                        .HasConstraintName("FK__Likes_Pla__IdPla__06CD04F7");

                    b.HasOne("FantaxyWebApplication.Models.Entities.User", "LoginOwnerNavigation")
                        .WithMany("LikesPlanets")
                        .HasForeignKey("LoginOwner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Likes_Pla__Login__05D8E0BE");

                    b.Navigation("IdPlanetNavigation");

                    b.Navigation("LoginOwnerNavigation");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.Planet", b =>
                {
                    b.HasOne("FantaxyWebApplication.Models.Entities.User", "CuratorLoginNavigation")
                        .WithMany("PlanetCuratorLoginNavigations")
                        .HasForeignKey("CuratorLogin")
                        .HasConstraintName("FK__Planets__Curator__403A8C7D");

                    b.HasOne("FantaxyWebApplication.Models.Entities.User", "OwnerLoginNavigation")
                        .WithMany("PlanetOwnerLoginNavigations")
                        .HasForeignKey("OwnerLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Planets__OwnerLo__3F466844");

                    b.Navigation("CuratorLoginNavigation");

                    b.Navigation("OwnerLoginNavigation");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.PlanetInfo", b =>
                {
                    b.HasOne("FantaxyWebApplication.Models.Entities.Planet", "IdPlanetNavigation")
                        .WithMany()
                        .HasForeignKey("IdPlanet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PlanetInf__IdPla__0E6E26BF");

                    b.Navigation("IdPlanetNavigation");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.PlanetRoleUser", b =>
                {
                    b.HasOne("FantaxyWebApplication.Models.Entities.PlanetRole", "IdRoleNavigation")
                        .WithMany("PlanetRoleUsers")
                        .HasForeignKey("IdRole")
                        .HasConstraintName("FK__PlanetRol__IdRol__59063A47");

                    b.HasOne("FantaxyWebApplication.Models.Entities.User", "UserLoginNavigation")
                        .WithMany("PlanetRoleUsers")
                        .HasForeignKey("UserLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__PlanetRol__UserL__5812160E");

                    b.Navigation("IdRoleNavigation");

                    b.Navigation("UserLoginNavigation");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.PlanetUser", b =>
                {
                    b.HasOne("FantaxyWebApplication.Models.Entities.Planet", "IdPlanetNavigation")
                        .WithMany("PlanetUsers")
                        .HasForeignKey("IdPlanet")
                        .HasConstraintName("FK__Planet_Us__IdPla__5535A963");

                    b.HasOne("FantaxyWebApplication.Models.Entities.User", "UserLoginNavigation")
                        .WithMany("PlanetUsers")
                        .HasForeignKey("UserLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Planet_Us__UserL__5441852A");

                    b.Navigation("IdPlanetNavigation");

                    b.Navigation("UserLoginNavigation");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.PlanetUsersInfo", b =>
                {
                    b.HasOne("FantaxyWebApplication.Models.Entities.Planet", "IdPlanetNavigation")
                        .WithMany("PlanetUsersInfos")
                        .HasForeignKey("IdPlanet")
                        .HasConstraintName("FK__PlanetUse__IdPla__440B1D61");

                    b.HasOne("FantaxyWebApplication.Models.Entities.User", "UserLoginNavigation")
                        .WithMany("PlanetUsersInfos")
                        .HasForeignKey("UserLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PlanetUse__UserL__4316F928");

                    b.Navigation("IdPlanetNavigation");

                    b.Navigation("UserLoginNavigation");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.Post", b =>
                {
                    b.HasOne("FantaxyWebApplication.Models.Entities.Planet", "IdPlanetNavigation")
                        .WithMany("Posts")
                        .HasForeignKey("IdPlanet")
                        .HasConstraintName("FK__Posts__IdPlanet__72C60C4A");

                    b.HasOne("FantaxyWebApplication.Models.Entities.User", "OwnerLoginNavigation")
                        .WithMany("Posts")
                        .HasForeignKey("OwnerLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Posts__OwnerLogi__73BA3083");

                    b.Navigation("IdPlanetNavigation");

                    b.Navigation("OwnerLoginNavigation");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.StatusesChat", b =>
                {
                    b.HasOne("FantaxyWebApplication.Models.Entities.Planet", "IdPlanetNavigation")
                        .WithMany("StatusesChats")
                        .HasForeignKey("IdPlanet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Statuses___IdPla__6EF57B66");

                    b.HasOne("FantaxyWebApplication.Models.Entities.Status", "IdStatusNavigation")
                        .WithMany("StatusesChats")
                        .HasForeignKey("IdStatus")
                        .HasConstraintName("FK__Statuses___IdSta__6FE99F9F");

                    b.Navigation("IdPlanetNavigation");

                    b.Navigation("IdStatusNavigation");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.StatusesPlanet", b =>
                {
                    b.HasOne("FantaxyWebApplication.Models.Entities.Planet", "IdPlanetNavigation")
                        .WithMany("StatusesPlanets")
                        .HasForeignKey("IdPlanet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Statuses___IdPla__6B24EA82");

                    b.HasOne("FantaxyWebApplication.Models.Entities.Status", "IdStatusNavigation")
                        .WithMany("StatusesPlanets")
                        .HasForeignKey("IdStatus")
                        .HasConstraintName("FK__Statuses___IdSta__6C190EBB");

                    b.Navigation("IdPlanetNavigation");

                    b.Navigation("IdStatusNavigation");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.UserStatusesStatus", b =>
                {
                    b.HasOne("FantaxyWebApplication.Models.Entities.UserStatus", "IdStatusNavigation")
                        .WithMany("UserStatusesStatuses")
                        .HasForeignKey("IdStatus")
                        .HasConstraintName("FK__UserStatu__IdSta__4AB81AF0");

                    b.HasOne("FantaxyWebApplication.Models.Entities.User", "UserLoginNavigation")
                        .WithMany("UserStatusesStatuses")
                        .HasForeignKey("UserLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__UserStatu__UserL__4BAC3F29");

                    b.Navigation("IdStatusNavigation");

                    b.Navigation("UserLoginNavigation");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.Chat", b =>
                {
                    b.Navigation("ChatFiles");

                    b.Navigation("ChatMessages");

                    b.Navigation("ChatsInfo");

                    b.Navigation("ChatsUsersChatRoles");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.ChatRole", b =>
                {
                    b.Navigation("ChatsUsersChatRoles");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.Comment", b =>
                {
                    b.Navigation("CommentsFiles");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.GlobalRole", b =>
                {
                    b.Navigation("GlobalRoleUsers");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.Planet", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("LikesPlanets");

                    b.Navigation("PlanetUsers");

                    b.Navigation("PlanetUsersInfos");

                    b.Navigation("Posts");

                    b.Navigation("StatusesChats");

                    b.Navigation("StatusesPlanets");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.PlanetRole", b =>
                {
                    b.Navigation("PlanetRoleUsers");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.Status", b =>
                {
                    b.Navigation("StatusesChats");

                    b.Navigation("StatusesPlanets");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.User", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Chats");

                    b.Navigation("ChatsUsersChatRoles");

                    b.Navigation("Comments");

                    b.Navigation("GlobalRoleUsers");

                    b.Navigation("GlobalUsersInfo");

                    b.Navigation("LikesPlanets");

                    b.Navigation("PlanetCuratorLoginNavigations");

                    b.Navigation("PlanetOwnerLoginNavigations");

                    b.Navigation("PlanetRoleUsers");

                    b.Navigation("PlanetUsers");

                    b.Navigation("PlanetUsersInfos");

                    b.Navigation("Posts");

                    b.Navigation("UserStatusesStatuses");
                });

            modelBuilder.Entity("FantaxyWebApplication.Models.Entities.UserStatus", b =>
                {
                    b.Navigation("UserStatusesStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
